let challange = '50 days of javascript';
console.log(challange);
console.log(challange.length);
console.log(challange.toUpperCase());
console.log(challange.toLowerCase());
console.log(challange.substring(0,2));
console.log(challange.slice(3));
console.log(challange.includes('script'));
console.log(challange.split(""));
console.log(challange.split(" "));
let social = 'Facebook, Google, Microsoft, Apple, IBM, Oracle, Amazon'; console.log(social.split(", "));
console.log(challange.replace('javascript', 'Python'));
console.log(challange.charAt(15));
console.log(challange.charCodeAt(11));
console.log(challange.lastIndexOf('a'));
let sent = 'you cannot end a sentence with because because because is a conjunction'; console.log(sent.indexOf('a'));
console.log(sent.lastIndexOf('because'));
console.log(sent.search('because'));
console.log(challange.trim());
console.log(challange.startsWith('50'));
console.log(challange.endsWith('t'));
console.log(challange.match(/a/g));
console.log(challange.concat('50 days of', ' javascript'));
console.log(challange.repeat(2));
